# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'FirstAid' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FirstAid
	
	pod 'Alamofire', '~> 4.7'
    pod 'IQKeyboardManagerSwift'
    pod 'SwiftyJSON'
    pod 'SDWebImage', '~> 4.0'
    pod 'Toast-Swift', '~> 3.0.1'
    #pod 'NotificationBannerSwift'
    pod 'NVActivityIndicatorView'
    pod 'GoogleMaps'
    pod 'GooglePlaces'
    pod 'ActionSheetPicker-3.0'
    # pod 'razorpay-pod', '1.0.16'
    pod 'XLPagerTabStrip', '~> 8.0'
    pod 'FMDB'
    pod 'CropViewController'
    
    pod 'Firebase/Core'
    pod 'Fabric'
    pod 'Crashlytics'
    pod 'GoogleSignIn'
    
    pod 'FacebookCore'
    pod 'FacebookLogin'

  target 'FirstAidTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FirstAidUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
